/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/Home/components/Fish': RouteRecordInfo<'/Home/components/Fish', '/Home/components/Fish', Record<never, never>, Record<never, never>>,
    '/Home/components/FoxGLTF': RouteRecordInfo<'/Home/components/FoxGLTF', '/Home/components/FoxGLTF', Record<never, never>, Record<never, never>>,
    '/Home/components/ImageFade': RouteRecordInfo<'/Home/components/ImageFade', '/Home/components/ImageFade', Record<never, never>, Record<never, never>>,
    '/Home/components/NeonRoom': RouteRecordInfo<'/Home/components/NeonRoom', '/Home/components/NeonRoom', Record<never, never>, Record<never, never>>,
    '/Home/components/ParallaxPlot': RouteRecordInfo<'/Home/components/ParallaxPlot', '/Home/components/ParallaxPlot', Record<never, never>, Record<never, never>>,
    '/Home/components/ProjectCard': RouteRecordInfo<'/Home/components/ProjectCard', '/Home/components/ProjectCard', Record<never, never>, Record<never, never>>,
  }
}
